/**
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */

import type { EditorThemeClasses } from "lexical";

const theme: EditorThemeClasses = {
  autocomplete: "bg-white border border-gray-300 shadow-md rounded-md p-2",
  blockCursor: "bg-black opacity-50",
  characterLimit: "text-red-500",
  code: "font-mono text-sm bg-gray-100 px-1 py-0.5 rounded",
  codeHighlight: {
    atrule: "text-purple-600",
    attr: "text-purple-600",
    boolean: "text-teal-600",
    builtin: "text-blue-600",
    cdata: "text-gray-500 italic",
    char: "text-pink-600",
    class: "text-blue-700",
    "class-name": "text-blue-700",
    comment: "text-gray-500 italic",
    constant: "text-indigo-600",
    deleted: "text-red-600 line-through",
    doctype: "text-gray-400 italic",
    entity: "text-gray-800",
    function: "text-blue-600",
    important: "text-pink-600 font-bold",
    inserted: "text-green-600",
    keyword: "text-purple-600 font-semibold",
    namespace: "text-yellow-600",
    number: "text-indigo-600",
    operator: "text-pink-600",
    prolog: "text-gray-400 italic",
    property: "text-teal-600",
    punctuation: "text-gray-800",
    regex: "text-green-600",
    selector: "text-blue-700",
    string: "text-green-600",
    symbol: "text-orange-500",
    tag: "text-pink-600",
    url: "text-blue-500 underline",
    variable: "text-yellow-600",
  },
  embedBlock: {
    base: "my-4 border border-gray-300 rounded-md",
    focus: "ring-2 ring-blue-500",
  },
  hashtag: "text-blue-500",
  heading: {
    h1: "text-3xl font-bold border-b border-gray-300 pb-2 mt-6 mb-4",
    h2: "text-2xl font-semibold border-b border-gray-300 pb-1 mt-5 mb-3",
    h3: "text-xl font-semibold mt-4 mb-2",
    h4: "text-lg font-semibold mt-4 mb-2",
    h5: "text-base font-semibold mt-4 mb-2",
    h6: "text-sm font-semibold mt-4 mb-2 uppercase tracking-wide text-gray-600",
  },
  hr: "my-6 border-t border-gray-300",
  hrSelected: "my-6 border-t-2 border-blue-500",
  image: "my-4 rounded-md max-w-full",
  indent: "ml-4",
  inlineImage: "inline-block align-middle max-w-[90%] rounded-md",
  layoutContainer: "flex flex-wrap gap-4",
  layoutItem: "flex-1 min-w-[200px]",
  link: "text-blue-600 underline hover:text-blue-800",
  list: {
    checklist: "list-none pl-0",
    listitem: "mb-1 ml-6",
    listitemChecked: "line-through text-gray-500",
    listitemUnchecked: "",
    nested: {
      listitem: "list-none",
    },
    olDepth: [
      "list-decimal pl-6 mb-4",
      "list-decimal pl-8",
      "list-decimal pl-10",
      "list-decimal pl-12",
      "list-decimal pl-14",
    ],
    ul: "list-disc pl-6 mb-0",
  },
  ltr: "text-left",
  mark: "bg-yellow-200",
  markOverlap: "bg-orange-200",
  paragraph: "text-base text-gray-900",
  quote: "border-l-4 border-gray-300 pl-4 italic text-gray-600 my-4",
  rtl: "text-right",
  specialText: "text-indigo-700 font-semibold",
  tab: "inline-block w-4",
  table: "table-auto border-collapse w-full my-4",
  tableAddColumns: "text-sm text-blue-500 underline cursor-pointer",
  tableAddRows: "text-sm text-blue-500 underline cursor-pointer",
  tableAlignment: {
    center: "text-center",
    right: "text-right",
  },
  tableCell: "border border-gray-300 px-4 py-2",
  tableCellActionButton: "text-xs text-blue-500 hover:underline",
  tableCellActionButtonContainer: "flex justify-end",
  tableCellHeader: "bg-gray-100 font-bold",
  tableCellResizer: "w-1 h-full bg-gray-300 cursor-col-resize",
  tableCellSelected: "bg-blue-50 border-blue-500",
  tableFrozenColumn: "bg-gray-50 sticky left-0",
  tableFrozenRow: "bg-gray-50 sticky top-0",
  tableRowStriping: "odd:bg-white even:bg-gray-50",
  tableScrollableWrapper: "overflow-x-auto",
  tableSelected: "outline outline-2 outline-blue-500",
  tableSelection: "bg-blue-100",
  text: {
    bold: "font-semibold",
    capitalize: "capitalize",
    code: "font-mono text-sm bg-gray-100 px-1 py-0.5 rounded",
    highlight: "bg-yellow-100",
    italic: "italic",
    lowercase: "lowercase",
    strikethrough: "line-through",
    subscript: "align-sub text-xs",
    superscript: "align-super text-xs",
    underline: "underline",
    underlineStrikethrough: "underline line-through",
    uppercase: "uppercase",
  },
};

export default theme;
